language: node_js

node_js:
  - 8
  - 10
  - 12

matrix:
  fast_finish: true

before_install:
  - npm --version

notifications:
  email: false
  slack:
    secure: e1o9RUnvMtdUKymfQorLu2VH/dfY8b/prWzVvyEVwyjCRzFKwQYrWMKEvi+PwXZIeZZ2KB3Vsr6qeArVykRyvr0uILTDt+zv78xR/zYmnUuQQnzdwB/4xvRbS/5TY2SlWVdxvRMwc9GWBvr8Cn6Ppi65jgPcB7Hidxfayf26ggCc/e+orTtbeKq13vcDDPmSXrAC5j0Dd58whF9b3H/Wo+DPfAA7RqqxGaGdkGuIRPFkrHc8XVpqHw9UENWeUs07iHjx/3mK28KiWlayrXgPIaEaWeLmyTo53JkgnRsmbkVyw6RMtb4n2nkim/AhCDmLC5tFzpwbMFAvDSfShSA/VJBVpAGnFHtLJ8IMCWAcsdtfF1e+l+8IHnTgeTrWC6BpJ0GiCbbvueXczeECbJxqKQ+ctwBURkcvMuAMdCtpVwdFPEbxJXEjJ5YbHdlaGHWpxn0qVlzXaWxdp9CcLk8xbEAXm0ntdaGZYtGEounyhLqp8eXC2u/ZRvvi/OkguYIIzxUndRVY3BWpicpaTL/wXRH0qbtXft6QlLSreKPlbIVQfAQLHwBXk0S732rWYcuXcJ22JKdXWEImtWXG4RvVJqoBHERezxKHVPlL4AwJm83wOfergP/udwRy1yD6WloeH1VevSYHxPtGF83/6THPU6ioHwvIEaze+tsI7Eg/26M=
cache:
  directories:
  - $HOME/.npm
